myWebsite/blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post

urlpatterns = [
    path('',
         ListView.as_view(
             queryset=
             Post.objects.all().order_by("-date")[:25],
             template_name = "blog.html"
         )
        ),
    path('<int:pk>/',
         DetailView.as_view(
             model = Post,
             template_name ="blog.html"
            )
         ), 
         
]

myWebsite/myWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('personal1.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')), 
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include('user_auth.urls')),
] 

myWebsite/personal1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),          # Landing page
    path('about/', views.about, name='about'),    # About page
    path('shopping/', views.shopping, name='shopping'), # Shopping page
]

myWebsite/polls/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myWebsite/user_auth/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'user_auth'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
    path('register/', views.register, name='register'),
    path('login/', views.authenticate_user, name='login'),
    path('user/', views.show_user, name='show_user'),
name='authenticate_user')

]

myWebsite/blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField()
    signature = models.CharField(max_length=140, default="Mr M")  # Added default parameter

    def __str__(self):
     return self.title  

myWebsite/personal1/models.py
from django.db import models

# Create your models here.

myWebsite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myWebsite/user_auth/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myWebsite/polls/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']
        widgets = {
            'pub_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

myWebsite/user_auth/forms.py
# Creating a registration form for user.

from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'password')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don’t match.')
        return cd['password2']

myWebsite/blog/views.py
from django.shortcuts import render

# Create your views here.

myWebsite/personal1/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, "about.html") 

def index(request):
    return render(request, 'index.html')

def shopping(request):
    return render(request, 'shopping.html')

myWebsite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice

# Create your views here.


def index(request):
    """
    Display the latest questions.
    """
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/polls.html", context)


def detail(request, question_id):
    """
    Display the details of a particular question.
    """
    question = get_object_or_404(Question, pk=question_id)    
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    """
    Display the results of a particular question.
    """
    response = f"You're looking at the results of question {question_id}"
    return HttpResponse(response % question_id)


def vote(request, question_id):
    """
    Handle voting for a particular question.
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
        'question': question,
        'error_message': "You didn't select a choice."
        })  
    else:
        selected_choice.votes += 1
        selected_choice.save()
      # Always return an HttpResponseRedirect after successfully
      # dealing with POST data. This prevents data from being
      # posted twice if a
      # user hits the Back button.
        return HttpResponseRedirect(
        reverse('polls:results', args=(question_id,))
        )

myWebsite/user_auth/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import UserRegistrationForm  # importing the registration form
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from .models import Choice, Question
from django.contrib.auth.models import User

def user_login(request):
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is None:
            return HttpResponseRedirect(reverse('user_auth:login'))
        else:
            login(request, user)
            return HttpResponseRedirect(reverse('polls:index'))  # Redirecting to polls app


def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password
    })


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return render(request, 'authentication/register_done.html', {'new_user': new_user})
    else:
        form = UserRegistrationForm()
    return render(request, 'authentication/register.html', {'form': form}) 


# Restricting voting to users logged-in .
@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myWebsite/blog/templates/blog.html
{% extends "header.html"%} 
{% block content %}
{% for post in posts %}
    <div>
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <h5>{{ post.date|date:"Y-m-d" }} <a href="/blog/{{ post.id }}">Read more</a></h5>
    </div>
{% endfor %} 

{%endblock%}

myWebsite/blog/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Blog{% endblock %}</title>
</head>
<body>
    <h1>A Warm Welcome</h1>
    {% block content %}
    {% endblock %}
</body>
</html>

myWebsite/blog/templates/post.html
{% extends "header.html" %}
{% block content %}
<h3><a href="/blog/{{post.id}}"> {{post.title}} </a></h3>
<h6> on {{post.date}}</h6>
<div class="container">
    {{post.body|safe|linebreaks}}
</div>
<br><br>
{%endblock%}

myWebsite/personal1/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Me</title>
</head>
<body>
    <h1>About Me</h1>
    <p>Name : Mahmood Chalamanda </p>
    <p>Occupation: Software Engineer</p>
    <p>Hobbies: Coding, Reading, Soccer</p>
</body>
</html>

myWebsite/personal1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mahmood Chalamanda</title>
    <link rel="stylesheet" href="style.css"> 
    <style>
      p{
        font-size: 1.5em;
        text-align: center; 
      
      }
  
    </style>
  
</head>

<body>
    <div class="middle-container"> 
      <img class="top-cloud"src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\cloud.png.png" alt="cloud-img" width="200" height="200">
        <header><h1>Mahmood Chalamanda</h1> </header>
        <img class="bottom-cloud"src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\cloud.png.png" alt="cloud-img" width="200" height="200">
        <img src="profile-picture.jpg" alt="Professional picture" width="150">
        <h2>About Me</h2>
       <section>
        <p>Hey there! Lets get straight to it. Many would consider me to be a continuos learner which i agree on, Im a focused individual who continually seeks to enhance my skills and knowledge.
          Im eager to contribute to innovative projects and make a positive impact through software solutions. In a couple months i see myself mastering every aspect that deals with software engineering
          and i am confident that i can make a significant contribution to your team.
      </p>
       </section> 
        <h2>Work Experience</h2>
        <h3>Entrepreneur (2022-Present)</h3>
        <p>After covid i noticed how many transactions have been moved to online and started my own retail online business. This gave the opportunity to focus on customer satisfaction and the importance of always bringing your best to the table.</p>
          
        <h2>Education</h2>
        <ul>
            <li>
                <h3>Self-taught, with the help of hyperion dev Boot-camp and online resources</h3>
            </li>
        </ul>
        <h2>Skills</h2> 
        <img class="Skill1" src="https://media.giphy.com/media/juua9i2c2fA0AIp2iq/giphy.gif" alt="coding-img">
        <ul>
            <li>HTML/CSS</li>
            <li>JavaScript</li>
            <li>Python</li>
            <li>Problem-solver</li>
            <li>Team Management</li>
        </ul>
        <hr>
        <div class="contact-me">
          <h2>Get In Touch</h2>
          <h3>How to contact me :</h3>
          <p>Let's create and develop together!</p>
          <a class="btn" href="mailto:mahmoodhc11@gmail.com">CONTACT ME</a>
        </div>
      </div>
    
      <div class="bottom-container">
        <a class="footer-link" href="https://www.linkedin.com/in/mahmood-chalamanda-44a6b91b9/?originalSubdomain=za">LinkedIn</a>
        <a class="footer-link" href="https://twitter.com/">Twitter</a>
        <p class="copyright">© Mahmood Chalamanda.</p>
      </div> 

      <form action="" method="get">
        <label for="search">Search my CV:</label>
        <input type="search" id="search" name="q" placeholder="Enter keywords...">
        <button type="submit">Search</button>
      </form> 
      <form action="/contact" method="post">
        <label for="name">Your Name:</label>
        <input type="text" id="name" name="name" required>
        <label for="message">Message:</label>
        <textarea id="message" name="message" required></textarea>
        <button type="submit">Send</button>
      </form>
</body>
</html>

myWebsite/personal1/templates/shopping.html
<!DOCTYPE html> 

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Affordable Luxury Shopping</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
            .product-img {
                transition: transform 0.5s;
            }
    
            .product-img:hover {
                transform: scale(1.1);
            } 
            .footer-form {
            padding: 20px 0;
            background-color: #f8f9fa;
        }
        </style>
    </head>
    <body> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Affordable Luxury</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="row">
        <div class="col-md-8"> 
            <br>
            <br>
            <br>
            <h3>Luxury meets affordability.</h3>

        </div> 
        <div class="col-md-4"> 
            
            <br>
            <br>
            <button type="button" class="btn btn-light"> Login </button> 
            <button type="button" class="btn btn-light"> Sign Up </button>
           

        </div> 


        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-1.jpg" class="img-fluid product-img" alt="Product 1">
                    <h6> Mens essential shirt</h6>
                    <p>R450 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-2.jpg" class="img-fluid product-img" alt="Product 2">
                    <h6> Mens Zara Jeans </h6>
                    <p>R550 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-3.jpg" class="img-fluid product-img" alt="Product 3">
                    <h6> Ladies Steve Madden Heels</h6>
                    <p> R 600 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-4.jpg" class="img-fluid product-img" alt="Product 4">
                    <h6> Zara Ladies Blazer</h6>
                    <p>R 650 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-5.jpg" class="img-fluid product-img" alt="Product 5">
                    <h6> Sherpa Throw Blanket</h6>
                    <p>R250 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-6.jpg" class="img-fluid product-img" alt="Product 6">
                    <h6> Mens co-ord</h6>
                    <p>R430 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-7.jpg" class="img-fluid product-img" alt="Product 7">
                    <h6> Zara Ladies Bag</h6>
                    <p>R 400 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-8.jpg" class="img-fluid product-img" alt="Product 8">
                    <h6> Ladies Formal Pants</h6>
                    <p>R 400 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-9.jpg" class="img-fluid product-img" alt="Product 9">
                    <h6> Mens Gallery Dept. shirt</h6>
                    <p>R 500 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
                <div class="col-md-2">
                    <img src="C:\Users\Zaeeda Chalamanda\Documents\Mahmood software engineering\Images\product-11.jpg" class="img-fluid product-img" alt="Product 10">
                    <h6> Mens Formal Shoes</h6>
                    <p>R600 </p> 
                    <button type="button" class="btn btn-primary"> Buy </button>
                </div>
            </div>
        </div> 

        <footer class="footer-form">
            <div class="container">
                <form class="row g-3">
                    <div class="col-md-4">
                        <label for="inputName" class="form-label">Name</label>
                        <input type="text" class="form-control" id="inputName" placeholder="Enter your name">
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail" class="form-label">Email</label>
                        <input type="email" class="form-control" id="inputEmail" placeholder="Enter your email">
                    </div>
                    <div class="col-md-4">
                        <label for="inputPhone" class="form-label">Phone</label>
                        <input type="tel" class="form-control" id="inputPhone" placeholder="Enter your phone number">
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-dark">Submit</button>
                    </div>
                </form>
            </div>
        </footer>

myWebsite/polls/templates/polls/detail.html
{% extends "polls/polls.html" %}

<h1> {{question.question_text}} </h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li> {{choice.choice_text}}</li>
    {% endfor %}
</ul> 

{% block content %}
  <h1>{{ question.question_text }}</h1>
  <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <button type="submit">Vote</button>
  </form>
  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}
{% endblock %}

myWebsite/polls/templates/polls/polls.html
{%if latest_question_list %} 

<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">
            {{question.question_text}}
        </a>
    </li>
    {% endfor%} 
</ul>
{%else%} 
<p> No polls are available</p>
{% endif%} 

myWebsite/user_auth/templates/authentication/login.html
<h1> Login as User </h1>

<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %} 

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    
    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>

    <input type="submit" value="Login" />
</form> 

myWebsite/user_auth/templates/authentication/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

myWebsite/user_auth/templates/authentication/register_complete.html
<!DOCTYPE html>
<html>
<head>
    <title>Registration Complete</title>
</head>
<body>
    <h1>Registration complete</h1>
    <p>Welcome, {{ new_user.username }}!</p>
</body>
</html>

myWebsite/user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>